### ISSUE TITLE
Nav bar needs to have its CSS fixed

### ISSUE THREAD

**Issue by ntoll** [checklisthq/checklisthq.com#16]
Nicholas knows how. It's a bootstrap issue that depends upon the order of referencing CSS files.

See: http://twitter.github.com/bootstrap/components.html#navbar for details.

**Comment by kalotay** [comment]
What is the actual problem with the navbar? Is it just the colour scheme?

**Comment by ntoll** [comment]
It's the `margin-top: 40px` problem relating to the `body` element that we discussed at the weekend. Stops the white space appearing when width is too small.
